language: python

matrix:
  include:
    - python: "3.6"

install:
  - if [ -z "$TRAVIS_TAG" ]; then exit 0;  fi
  - pip install awscli

script:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.29/hugo_0.29_Linux-64bit.tar.gz -O hugo.tar.gz
  - tar xvzf hugo.tar.gz
  - rm -rf "./public/"
  - ./hugo
  - aws s3 sync --acl public-read --sse --delete "./public/" s3://www.joc-gafo.org
  - coverage run --source=blockschaltbilder setup.py test
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id EPNLPWEUBLA8I --paths '/*'
env:
  global:
    - secure: kTrQRbIHOnv7QWgQUl4pEB2Nmeb+H1ey6QObzvBjrAHqtc8t61YrU6CuMAYwXOLD7c9Uc00yT+7u75+++qa7qxBNEPuAGoGN/QvptxVo6vzM5gpd2b3k3GwRm6E3dhJLbN1fr5yAaPRa7mXicVcdqYHhfqQrQhsnagTbWmz4QlgDg9ipLCCljBESnqBjp7rqoIjNMcaT+h/S6Ooj4kjjGI834+gPpAtN3UaHXsHlxc1ZEpC5FVwYroy+fxUBJFegUGnXnaQMpj1Jr5zS3zAEXP1B3rKTq5pV40a4dOFMMMvCJCt+IC8B0prShlaBXDp6IL7shbrd5I+T80YYsE7LpqV2w50lbTnm+kW/lbqhPj+PTnMyn3q4qrZql+o/PdjnxvgQ6KTgirRt9HOXrrRmXIn97OdzutGCQdUBkch1pJaDcv3nIapav1Gxt/5aie0gQi1lOd0xbVhEZQox/IWJGatngqiB3Mt2qq0JTDPtEHMBBaSQn2rcv1OBUKiV2Eabhatx/nxQuBcPbdWANgnyS4VAFImB7UUBaF6CMHoOfL0Z1HQQEQgakNLLUDObRGm4U+a4xd6lS0h3gHmR2ht3455nBnhocX3SdflMzc00V4O3QeuhhQoyC9MjozzU0vPDEWIi+wlxehiwXVF8UgffJ2xSBGx6+cmqK791cxTHzes=
    - secure: N0N0RYQElRae7WBfINgJ5dHTHGPCeOwupyrAnresjWWUEvQtFQHRuhwNUsUmSnGFJSSOYGUw+DWKU9RN2NSiQ976MZHqzZr37D2vMN3G0hLWk5j/BIIByC30aJ2hGHYGENOyvi74sHCAlHDSV3I4MSBthe7h0ORxcU2Vzs98mfW9jgdPIr2CDEwjije6LFCIDXSclz1w6XEmlsEmSLc3xvvSYkgRcYpFR/bRU6jeS9Uh+K+s4PPZjkW6QI3j8fPacRQl6k1vRz8DCDNWyqgmv5puEfeyUWGNiXOs1yZo11KjeGuYASopedfQg4WkGh/IjMmlvKVNk604JMMP4gGHAPYejhuDN9+gpPAo58DK5cXHa4Ey/PJD+A29fEW05nnHORj0Kog381tEtSEJNWSoxCCQJxgi0ZNVzb1VJg/7cWPPCPG+uC796VDrlWBAe6FqIj/ABZbZddHpoapxUaOeaTpkb6td2tgh4mapjnXUTup65uvb/iuSBdtIyhXpOZIJpnSMUc3DeBDztXcFmYxop7zseKl1Zby+Vr66YqRkzrUMT35lLX0RE6oHbucKf+4kRNZxAbTYcFdiS5RtiEQxwVffGC5z7R9Q6GX0LKnObg/W92mobr2MPhX9JyUB8zbuDbS4NG+HXv7qER0zZOySzgMf5keu9QmIW19l3098liM=
    - secure: oG/QTDGARaCBNGcaZCMrjXsthzWJnnZi22LSmdLSYmDuhg1DIkedXL0aMuU621lGvgIPMLBJc2T2KC3kHmJuAtlQaUi/wuHekfZH96Euy6ftIYKt5ym1kUqZa3K/jScbWkE8lAmM9w7Jb6BGYmPuvyffr01BjEXf4kw28a1NFEuWUC7gcmCIoUIAH25mZ7fRB2uFUKmAXiijY26vLYCNF4gL9uoLesO0thxPErxvwm/OFloTdvZyJOpn+wsNl6YAMvBxPuCJCOgeMsnGFg90WsLsyhd+fMksydQsAl+xe5feNinHMp0E/Q2bEDwIqBYpO1W9mH2CV6aIY2xKhgld9fEmX+2TlTiEGahbgYnbvZkTUcurOAmf9mA8mBcTiyIX7MhDGGUiWjMn6dXc9UdjmTtWzKDB5ZnWrjsMo2rkABByRJHgYtc2XGi6/IzPsq3iOxD7sUDCevaBnvUu0pK9Fnp9XxBho8qdylzmT5qv5H5ATSPYJbV0Gu8xBJvX9PDY5U8IVRMMUOO4lSGvjIgY63GiU/3KX/9xljql0MRgDWOozzIuYiqNnxUsphUUFTT80+fnHc6i/FmVKhiVNkfNqnLSnP5oJqzNB7FmiHSU1ByyG2g/j8eljXClFxAeFQ4zsCG0kB8x4IHLX4WVEf+XDmKwRWCGWterwEEdBB7O8Z8=
