language: python
python: '3.5'
cache: pip

before_install:
  - if [ -z "$TRAVIS_TAG" ]; then exit 0; fi

install:
  - pip install awscli

script:
  - aws configure set preview.cloudfront true
  - aws s3 sync s3://joc-gafo-binaries "./static/img/"
  - wget https://github.com/gohugoio/hugo/releases/download/v0.29/hugo_0.29_Linux-64bit.tar.gz -O hugo.tar.gz
  - tar xvzf hugo.tar.gz
  - rm -rf "./public/"
  - "./hugo"
  - aws s3 sync --acl public-read --sse --delete "./public/" s3://www.joc-gafo.org
  - aws cloudfront create-invalidation --distribution-id EPNLPWEUBLA8I --paths '/*'

env:
  global:
    - secure: Z04uwDnEkEr2JO0EkIn6zQVtYB0uk7NGd/lcHfF7pjXa51iG0Ew/779otw3Stv2Y/bgsSrBIz+1KBY2kaTfdJagsA4LviUMmo2OmqMwaq3ABnX4eVPRZZByEe6LG+GHQm80+jnJ6gJFNG65FC2AbmuqpTYzo2KShJYdRdPiy9DXCtO8DO9Xp0QTDUTLj97DSWlQ9q+b36q0JhnUp0Tak/+niozjJvaZqbTPTd2eUkk8aaW8VWJYqdq4vqGCBIr1VPWwKXggwK0AzjBRbUkhnV8wmzqI+NzPveu21uDNRkOEjaA87bSIqgzQLxWy9zn8FunqhPTt46eu5s88qO+IGQT//225mpNK0lhcW87vP7cu1Y1XDvl1PamJVGsjg66c9hXOvrlRpkiTWcmIqtjTINwv26Bl0ThSj3BIknvebLApKiP5cQSG4qzCNFEA+SwE8+n35I9smXrlM0k+SeJ8zQs70/o7fWnc3SWMnFHd/buzL26+yHhDaMKPcgGxfXJZa/hGFfDB4co6K9Anl6kdD5rO6Bc4LujImCoMTb5W4BnO9mAJAJbnSPE2QezfZxyUs9kG6bIMMeXnLhMvaZN4xPFPf/9F9sij2ch5h/q2LLxxZjGKJWjG4gQ9ixC+4qgQKJjI9SZ3BJv7aGyRtLxQKXpV4p2hzFVR7GRBBBkLXRCo=
    - secure: VQ37QKJNvU9vj4a0hib7bu8f5dTW1I/Phmp0zxKCnLoaakhawnf0+oJuNcxtjE6L/t8W1YCfkSCHdQy2iZkd1GSImKsGvkdvy6L3jgA9Z+WyeHcKl5jeR2ffydpCrCNdiGts2i+Ok3BFAQN9vHNP2IqpQc6vRA/p5BuFRTA/+C6G7iazcICeK0zHYMP3FN6rrtZmh773uKPaaYq7lK1WJuEcdF2l8UxXG9MAnhNssEeJjL73AL6uYqhDj3gGRbH43SnJTvGQj8ppuHDSD4gMMQUzrpE4E5gTXwDQd6dQXL7IPL1Hi76FsGSrb/6l7lYSduQyxI4Q+OIpKI7jyf/RSsmbiOFs1ERIVBJvkZ1iFJtHu3jaHFX2Z4Wi1qU4FMO2kkg0PyVKshNbdL+7G0eE9iYVBSRzm3/gFMGcYoVK83/2/0gnbWtPlOO6Obg/lL6EV1yphPnzg6jEWm/Y25MgWneZ3vKvnnpGG5qhzIVJ1/EkXn7r4ZmAuiE/n9AksXrXkghmec/46qIksMQfVXu8oLxa7ZhVWdyzigxyIJVObe3SHtNoxFZusXQBuI4f0ag5biLXkFn/zcS3CJ0bry9bKqOWR8Fj2PZRJo/vyqXRMp3awhvc50n35DhplFXgfYfAz05QrlNg3gEUNCkUyE1HMbvSZE3UXOyhTueKcOCpmPs=
    - secure: PqBMhvzuPd40XXi1FYDqdnqaZbcxT46hjZtfSr+kq51+xsjwnmXX88D20Dq7QEGXoOQrlAeQet4BVpKhHyNxyTCfaHFTFym75M5OCkNLwyFqIVnE++gm79utOhimBq+Kwtkch2VPZaw16ESzrQNzKM/DWHw2tB+NfI2BT8zKgOSoQg/dhM3wYpUo2PA2bM3Xn2p78AY254qQikdN0VtAmwX2GKZjYR9dts/yxApT+Ku+oddZCnDoda/TUnP6rhy0IL3L23egQCB+d6isYbLlj0m/kqjG4N+YxkXJj2ID4oKk8AX1lJkQApnTEm3F4CYcnnegzUo3TQfLxH1a5/a7rcipmAv3EoO6MiNZRASh3OVhFZVSk1hr5aDOsZ8cscq11E0fRol+zp9wih7hPElZs5AB31EJ84RHUbYf32Cx7zU5uMzQUXbTFjdN8QKRHy0Y2xsrJT+d6NXKTiX1kl46BLulI/1aFuRf3K+VS2/k88Y6bu+KaQlk2Tavi/lxG/pH5cDVvbbBriDcY/Z3YKqLlYA4xD/gcEbMy7aeYiY28GeJUWBhhfVV3+4WsLRAckxTGvHdMT18ySff4f9ASH4nJzq/PwKL8sojx7kDuhImsPgVlB04COcaH73hekpDSeUDcOXzerDik53xP5u5qRdgeQwmye1hyPQZjkGqKACWEgU=
